name: trip
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.4
  get: 4.6.1
  intl: ^0.17.0
  flutter_typeahead: ^3.2.4
  carousel_slider: ^4.0.0
  jiffy: ^5.0.0
  get_storage: ^2.0.3
  firebase_auth: ^3.3.11
  firebase_core: ^1.13.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.4
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/png/
    - assets/images/jpg/

